using System.Collections.Generic;


namespace GestaodeVoluntarios.UI.Models.Feminino
{
    public class FemininoCadastro : EntidadeBasica
    {
        public int? FemininoCadastroId { get; set; }
        public string CadastroDataInclusao { get; set; }      
        public string CadastroNome { get; set; }
        public string CadastroRG { get; set; }
        public string CadastroClasseSocial { get; set; }
        public string CadastroObsGerais { get; set; }
        public string CadastroObs1 { get; set; }
        public string CadastroObs2 { get; set; }
        public string CadastroObs3 { get; set; }
        public string CadastroDataNascimento { get; set; }
        public int? CadastroIdade { get; set; }
        public string CadastroTelefoneResidencial { get; set; }
        public string CadastroTelefoneCelular { get; set; }
        public string CadastroTelefoneComercialRecado { get; set; }
        public string CadastroTelefoneWhatsapp { get; set; }
        public string CadastroTelefoneDiversos { get; set; }
        public string CadastroCapacidadeSentirCheiro { get; set; }
        public string CadastroDiabetico { get; set; }
        public string CadastroFumante { get; set; }
        public string CadastroAlergiaSimNao { get; set; }
        public string CadastroAlergiaQual { get; set; }
        public string DadosPessoaisCPF { get; set; }
        public string DadosPessoaisCEP { get; set; }
        public string DadosPessoaisLogradouro { get; set; }
        public string DadosPessoaisNumero { get; set; }
        public string DadosPessoaisComplementoBlocoApto { get; set; }
        public string DadosPessoaisBairro { get; set; }
        public string DadosPessoaisCidade { get; set; }
        public string DadosPessoaisUF { get; set; }
        public string FilhoSexo1 { get; set; }
        public string FilhoDataNascimento1 { get; set; }
        public string FilhoSexo2 { get; set; }
        public string FilhoDataNascimento2 { get; set; }
        public string FilhoSexo3 { get; set; }
        public string FilhoDataNascimento3 { get; set; }
        public string FilhoSexo4 { get; set; }
        public string FilhoDataNascimento4 { get; set; }
        public string FilhoSexo5 { get; set; }
        public string FilhoDataNascimento5 { get; set; }
        public string FilhoSexo6 { get; set; }
        public string FilhoDataNascimento6 { get; set; }
        public string EnsinoFundamentalCompleto { get; set; }
        public string EnsinoMedioCompleto { get; set; }
        public string EnsinoSuperiorCompleto { get; set; }
        public string EnsinoPosGraduacaoCompleta { get; set; }
        public string ProfissaoNomeEmpresa { get; set; }
        public string ProfissaoProfissao { get; set; }
        public bool Gravida { get; set; }
        public bool Amamenta { get; set; }
        public bool LencoUmidecidoInfantil { get; set; }
        public bool LencoUmidecidoIntimo { get; set; }
        public bool LencoUmidecidoMaquiagem { get; set; }
        public bool SaboneteCorporalBarra { get; set; }
        public bool SaboneteCorporalLiquido { get; set; }
        public bool SaboneteCorporalIntimo { get; set; }
        public bool SaboneteFacialBarra { get; set; }
        public bool SaboneteFacialLiquido { get; set; }
        public bool SaboneteFacialEsfoliante { get; set; }
        public bool SaboneteFacialGel { get; set; }
        public bool SaboneteFacialEspuma { get; set; }
        public bool HigieneBucalCremeDental { get; set; }
        public bool HigieneBucalEscovaDental { get; set; }
        public bool HigieneBucalFioDental { get; set; }
        public bool HigieneBucalEnxaguante { get; set; }
        public bool DesodoranteCorporalAerosol { get; set; }
        public bool DesodoranteCorporalCreme { get; set; }
        public bool DesodoranteCorporalRollOn { get; set; }
        public bool DesodoranteCorporalSpray { get; set; }
        public bool HidratanteCorporal { get; set; }
        public bool HidratanteFacial { get; set; }
        public bool HidratanteMao { get; set; }
        public bool HidratantePe { get; set; }
        public bool HidratanteParaBanho { get; set; }
        public bool HidratanteOleoCorporal { get; set; }
        public bool Bronzeador { get; set; }
        public bool ProtetorSolarCorporal { get; set; }
        public bool ProtetorSolarFacial { get; set; }
        public bool ProtetorSolarLabial { get; set; }
        public bool ProdutosCabeloShampoo { get; set; }
        public bool ProdutosCabeloShampooAntiCaspa { get; set; }
        public bool ProdutosCabeloCondicionador { get; set; }
        public bool ProdutosCabeloCondicionadorAntiCaspa { get; set; }
        public bool ProdutosCabeloCremePentear { get; set; }
        public bool ProdutosCabeloMascaraTratamento { get; set; }
        public bool ProdutosCabeloGel { get; set; }
        public bool ProdutosCabeloFinalizador { get; set; }
        public string TipoPeleFototipo { get; set; }
        public string TipoPeleRosto { get; set; }
        public string TipoPeleBracoPerna { get; set; }
        public string TipoPeleMaoPe { get; set; }
        public string TipoPeleCostaPeitoral { get; set; }
        public string TipoPeleObservacao { get; set; }
        public string UnhaApta { get; set; }
        public string UnhaSeNaoPorque { get; set; }
        public string UnhaComprimento { get; set; }
        public string UnhaUsoFrequenteEsmalte { get; set; }
        public string UnhaCuticulasIntegra { get; set; }
        public string UnhaEspessura { get; set; }
        public string UnhaSudorese { get; set; }
        public string UnhaObservacao { get; set; }
        public string DetalhesCabeloApta { get; set; }
        public string DetalhesCabeloAptaSimNaoPorque { get; set; }
        public string DetalhesCabeloOndeColore { get; set; }
        public string DetalhesCabeloMegaHairAplique { get; set; }
        public int? DetalhesCabeloCorNatural { get; set; }
        public int? DetalhesCabeloCorIntermedio { get; set; }
        public int? DetalhesCabeloCorPontas { get; set; }
        public int? DetalhesCabeloNuance { get; set; }
        public string DetalhesCabeloFiosBrancosPorcentagem { get; set; }
        public string DetalhesCabeloComprimento { get; set; }
        public string DetalhesCabeloEspessura { get; set; }
        public string DetalhesCabeloCurvatura { get; set; }
        public int? DetalhesCabeloLavagemCabelo { get; set; }
        public string DetalhesCabeloCondicao { get; set; }
        public string DetalhesCabeloObservacaoCapilar { get; set; }
        public bool CabeloTransfQuimicaNaoVirgemNatural { get; set; }
        public bool CabeloTransfColoracaoTonalizante { get; set; }
        public bool CabeloTransfPermanente { get; set; }
        public bool CabeloTransfDescoloracaoReflexoLuzesMechas { get; set; }
        public bool CabeloTransfEscovaProgressiva { get; set; }
        public bool CabeloTransfLuzesOuAlisamento { get; set; }

    }
}
